### PR TITLE
feat(cci): dockerize it

### PR DESCRIPTION
**Pull request by heralight**

### CODE REVIEW

**Comment by jstaf** [comment]
I have been considering doing this, can you explain the use case a little bit better? The main reason I've been avoiding dockerizing onedriver thus far is that the resulting docker image requires a significant number of special privileges to run and mounting several volumes (there are so many special docker privileges required because onedriver actually needs to talk to the docker host's kernel directly, so it's almost as if it's not running via docker at all). It would also need to be a headless build, so we'd lose the authentication GUI. 

Re: containerizing it, my current thinking is I'd create a flatpak for use with Linux desktop systems that can't use the prepackaged rpm/deb/AUR builds. Does this cover your use case, or did you have something else in mind?

**Comment by jstaf** [comment]
Oh nevermind, I can't read. This is a PR, not an issue. I'll take a look :sweat_smile:

**Comment by heralight** [comment]
Hello @jstaf , thank you for this project!
Unfortunately I did some backup tests with onedriver, in direct or through docker, and the result was not so good, then I stop the experimentation here. For exemple on file bigger than 200Mo, the process crash.

This pull request is to not lost the code that I wrote to test it and share it. 

From my side, I switch to rclone with its webdav server new feature, I didn't reproduce the problems that I had with onedriver.

Best regards,

Alexandre

**Comment by jstaf** [comment]
I did some more thinking on this one and I don't think a docker container is the right way to package this:

* Every piece of onedriver's functionality relies on stuff that fundamentally cannot live in a docker container (host kernel+host cache folder+host mountpoint+systemd for the filesystem itself and dbus+wayland/x11 sessions for the GUI). If you set all of this up, it's as if it's not running in a docker container at all, which kind of defeats the purpose of putting it in a container in the first place.
* It's easier to just build the Go binary from source than it is to build and run a docker image, and the docker image is less portable than what the Go compiler can do via cross-compilation.
* I'm still not sure what the use case is for docker here. The only situation that would really require a docker container is running this on Kubernetes to expose OneDrive to some other container, which is crazy (you should be connecting to Microsoft Graph API directly if you need it for another application). 

For what it's worth, if you share the logfile for the crash, I can fix it. (Please open a new issue for that one :slightly_smiling_face:)

**Pull request closed without merging**
