### PR TITLE
A little clarification

### PR DESCRIPTION
**Pull request by dipunm**
As a user, I felt that there were some steps missing from this documentation. 

I initially didn't install go, I think adding a link will highlight that part of the README and make it obvious that you will need to have go installed.

Also, since I didn't go through the build and test steps, I had to work out how to get onedriver configured, so I added that to the readme too.

### CODE REVIEW

**Comment by jstaf** [comment]
Hi @dipunm - I added a link to installing Go in the readme. The `onedriver -a` step actually isn't necessary - onedriver will set up the authentication automatically when you run it for the first time (either through running `onedriver` or starting things via `systemctl`). Is it alright if I close this PR?

(I'm actually going to start providing rpm/deb/binary packages in the next release, which should make onedriver significantly easier to install. Hoping to add a little GUI setup tool which will help users pick a mountpoint and confirm that their credentials are setup correctly as well.)

**Comment by dipunm** [comment]
Sure, it was a tiny contribution. Although honestly I had to see the logs to find out why the program wasn't working first time. If the first thing to run the application was systemctl, there is no way for the user to input the authentication token, hence why I think we still need to add the `-a` line.

**Comment by jstaf** [comment]
Ah, when you compiled it, did you have webkit2gtk3 installed (see the readme for instructions for Ubuntu/Fedora)? When you compile with webkit2gtk3, it *should* make a nice pop-up web browser to do the authentication, even when started with systemctl. 

(Hopefully this gets a lot easier once I start providing binaries.)

**Comment by dipunm** [comment]
I'm pretty sure I did run (on ubuntu) `apt install golang gcc pkg-config libwebkit2gtk-4.0-dev` but now I'm not sure 100% since I see `golang` there, and I did re-format and re-install this, I may have missed it the second time around.

I will double check by next week, I'm happy for you to close this and if I find it to be an issue, I'll create an issue :)

**Comment by jstaf** [comment]
I actually just created some precompiled binaries you can use for installation now, check out the releases page here: https://github.com/jstaf/onedriver/releases. (Hoping to have a GUI to automate setup for a future release.)

**Pull request closed without merging**
